version: "3.3"

services:
  backend-api:
    build: ./backend
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn run dev"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    networks:
      - api

  frontend-app:
    stdin_open: true
    build: ./frontend
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn start"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend-api
    ports:
      - 3000:3000
    networks:
      - api

networks:
  api:

